services:
  relay:
    build:
      context: .
      dockerfile: docker/dockerfile
    env_file:
      - .env
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./:/src
    ports:
      - 8000:8000
    depends_on:
      - db
      - cache

  # PostgreSQL service
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5420:5432
    volumes:
      - relay_db:/var/lib/postgresql/data

  # Dragonfly cache service
  cache:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    restart: always
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - dragonfly:/data

  # RedisInsight
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/db
    restart: always
    depends_on:
      - cache


volumes:
  relay_db:
  dragonfly:
  redisinsight:
