[project]
name = "relay"
version = "0.1.0"
description = "Simple yet effective open source LLM Studio."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.0",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.115.4",
    "pydantic>=2.9.2",
    "pydantic-settings>=2.6.1",
    "sqlalchemy>=2.0.36",
    "greenlet>=3.1.1",
    "loguru>=0.7.2",
]

[dependency-groups]
providers = [
    "anthropic>=0.39.0",
]
dev = [
    "ipdb>=0.13.13",
    "pre-commit>=4.0.1",
    "ruff>=0.7.2",
]
