[project]
name = "relay"
version = "0.1.0"
description = "Simple yet effective open source LLM Studio."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.1",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.115.9",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "sqlalchemy>=2.0.38",
    "greenlet>=3.1.1",
    "loguru>=0.7.3",
    "sentry-sdk[fastapi,sqlalchemy]>=2.22.0",
    "redis[hiredis]>=5.2.1",
    "aiofiles>=24.1.0",
    "python-multipart>=0.0.20",
    "pillow>=11.1.0",
    "pybase64>=1.4.0",
    "mcp[cli]>=1.3.0",
]

[dependency-groups]
providers = [
    "anthropic>=0.48.0",
    "ollama>=0.4.7",
    "openai>=1.65.1",
]
dev = [
    "ipdb>=0.13.13",
    "pre-commit>=4.1.0",
    "ruff>=0.9.8",
    "tomli-w>=1.2.0",
]
mcp-servers = [
    "mcp-server-time>=0.6.2",
    "mcp-tavily>=0.1.2",
]
