name: 🐛 Relay Serve Bug
description: Report a bug or unexpected behavior in Relay Serve
labels: ["need confirmation"]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to Relay Serve! ✊

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Just making sure you're using the latest version of Relay Serve.
      options:
        - label: I confirm that I'm using the latest version of Relay Serve
          required: true
        - label: I confirm that I searched for my issue in https://github.com/yamanahlawat/relay-serve/issues before opening this issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible. 🙏
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Python, Pydantic AI version
      description: |
        Which version of Python and Pydantic AI are you using?
      render: Text
    validations:
      required: true
