"""remove_sse_from_servertype_enum

Revision ID: 2ee13cbe8dbf
Revises: e08d584030f3
Create Date: 2025-07-16 18:31:49.709071

"""

from typing import Sequence, Union

from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "2ee13cbe8dbf"
down_revision: Union[str, None] = "e08d584030f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servertype",
        new_values=["STDIO", "STREAMABLE_HTTP"],
        affected_columns=[TableReference(table_schema="public", table_name="mcp_servers", column_name="server_type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="servertype",
        new_values=["STDIO", "SSE", "STREAMABLE_HTTP"],
        affected_columns=[TableReference(table_schema="public", table_name="mcp_servers", column_name="server_type")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
