"""Added SessionFact table and Added memory metadata to Message Model

Revision ID: 678d2e646d11
Revises: 2ee13cbe8dbf
Create Date: 2025-10-06 16:33:31.200442

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "678d2e646d11"
down_revision: Union[str, None] = "2ee13cbe8dbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("fact_type", sa.String(length=50), nullable=False),
        sa.Column("fact_text", sa.Text(), nullable=False),
        sa.Column("source_message_id", sa.Uuid(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.Column("superseded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_message_id"], ["chat_messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["superseded_by"], ["session_facts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_facts_fact_type"), "session_facts", ["fact_type"], unique=False)
    op.create_index(op.f("ix_session_facts_id"), "session_facts", ["id"], unique=False)
    op.create_index(op.f("ix_session_facts_is_active"), "session_facts", ["is_active"], unique=False)
    op.create_index("ix_session_facts_session_active", "session_facts", ["session_id", "is_active"], unique=False)
    op.create_index(op.f("ix_session_facts_session_id"), "session_facts", ["session_id"], unique=False)
    op.create_index(
        "session_facts_embedding_hnsw_idx",
        "session_facts",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.add_column("chat_messages", sa.Column("importance_score", sa.Float(), server_default="0.0", nullable=False))
    op.add_column("chat_messages", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column("chat_messages", sa.Column("memory_tier", sa.String(length=20), nullable=True))
    op.add_column(
        "chat_messages",
        sa.Column("extracted_facts", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
    )
    op.create_index(op.f("ix_chat_messages_importance_score"), "chat_messages", ["importance_score"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_importance_score"), table_name="chat_messages")
    op.drop_column("chat_messages", "extracted_facts")
    op.drop_column("chat_messages", "memory_tier")
    op.drop_column("chat_messages", "summary")
    op.drop_column("chat_messages", "importance_score")
    op.drop_index(
        "session_facts_embedding_hnsw_idx",
        table_name="session_facts",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_session_facts_session_id"), table_name="session_facts")
    op.drop_index("ix_session_facts_session_active", table_name="session_facts")
    op.drop_index(op.f("ix_session_facts_is_active"), table_name="session_facts")
    op.drop_index(op.f("ix_session_facts_id"), table_name="session_facts")
    op.drop_index(op.f("ix_session_facts_fact_type"), table_name="session_facts")
    op.drop_table("session_facts")
    # ### end Alembic commands ###
