"""Update ChatMessage content and attachments to make one optional

Revision ID: 6c2d9c0a299b
Revises: f82efbf53d49
Create Date: 2025-02-07 15:03:44.022888

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c2d9c0a299b"
down_revision: Union[str, None] = "f82efbf53d49"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat_messages", "content", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chat_messages", "content", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
