"""Added database models for LLM Providers and LLM Models

Revision ID: 78e7f8a810e5
Revises:
Create Date: 2024-11-11 12:55:19.583505

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "78e7f8a810e5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_providers",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("api_key", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_provider_name"),
    )
    op.create_index(op.f("ix_llm_providers_id"), "llm_providers", ["id"], unique=False)
    op.create_index(op.f("ix_llm_providers_name"), "llm_providers", ["name"], unique=False)
    op.create_table(
        "llm_models",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("top_p", sa.Float(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_cost_per_token", sa.Float(), nullable=False),
        sa.Column("output_cost_per_token", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["llm_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "name", name="uq_provider_model"),
    )
    op.create_index(op.f("ix_llm_models_id"), "llm_models", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_models_id"), table_name="llm_models")
    op.drop_table("llm_models")
    op.drop_index(op.f("ix_llm_providers_name"), table_name="llm_providers")
    op.drop_index(op.f("ix_llm_providers_id"), table_name="llm_providers")
    op.drop_table("llm_providers")
    # ### end Alembic commands ###
