"""Make api_key optional

Revision ID: fdaa184ab7c7
Revises: 4c47b832eeff
Create Date: 2024-11-19 03:42:34.214158

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdaa184ab7c7"
down_revision: Union[str, None] = "4c47b832eeff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_providers", "api_key", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("llm_providers", "api_key", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
